import type { Metadata } from "next";
import '@/styles/globals.css'
import MainLayout from "@/components/layout/MainLayout";

import 'swiper/css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainGroupLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainLayout>
      {children}
    </MainLayout>
  );
}
