import type { Metadata } from "next";
import '@/styles/globals.css'


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
            >
                {children}
            </body>
        </html>
    );
}
