import type { Metadata } from "next";
import '@/styles/globals.css'
import MainLayoutManage from "@/components/layout/manage/MainLayoutManage";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
            >
                <MainLayoutManage>
                    {children}
                </MainLayoutManage>

            </body>
        </html>
    );
}
